pipeline:
  name: nodejs-ci-pipeline
  identifier: nodejs_ci_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build and Test Node App
        identifier: Build_and_Test_Node_App
        description: "Build, test, and validate Node.js application"
        type: CI
        spec:
          cloneCodebase: true
          # Enable Cache Intelligence for faster builds
          caching:
            enabled: true
          # Using Harness Cloud build infrastructure
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              # Step 1: Install dependencies
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Sh
                    command: |
                      cd nodejs
                      npm ci
                    
              # Step 2: Run linting (optional - add eslint to package.json if needed)
              - step:
                  type: Run
                  name: Lint Code
                  identifier: lint_code
                  spec:
                    shell: Sh
                    command: |
                      cd nodejs
                      npm run lint

              # Step 3: Run unit tests with JUnit report
              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests
                  spec:
                    shell: Sh
                    command: |
                      cd nodejs
                      npm test
                    # Report test results to Harness
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - nodejs/junit.xml

              # Step 4: Run tests with coverage (optional)
              - step:
                  type: Run
                  name: Run Tests with Coverage
                  identifier: run_tests_coverage
                  spec:
                    shell: Sh
                    command: |
                      cd nodejs
                      npm run test:coverage
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - nodejs/junit.xml

              # Step 5: Build step (if applicable)
              - step:
                  type: Run
                  name: Build Application
                  identifier: build_application
                  spec:
                    shell: Sh
                    command: |
                      cd nodejs
                      npm run build

              # Step 6: Build and Push Docker Image to Docker Hub
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to Docker Hub
                  identifier: build_and_push_docker
                  spec:
                    connectorRef: DockerHub_Connector
                    repo: <+pipeline.variables.dockerhub_username>/nodejs-harness-demo
                    tags:
                      - <+pipeline.sequenceId>
                      - latest
                    dockerfile: nodejs/Dockerfile
                    context: nodejs

  variables:
    - name: dockerhub_username
      type: String
      description: Your Docker Hub username
      required: true
      value: <+input>

  properties:
    ci:
      codebase:
        connectorRef: Github_Personal
        repoName: harnessci
        build: <+input>